version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: yahoo_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  traffic-generator:
    build: ./traffic_generator
    volumes:
      - ./dataset:/data
    depends_on:
      - llm-service

  llm-service:
    build: ./llm_service
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_API_KEY=AIzaSyAQ8EoZk_R9zOYq3FiT2Sei3Y6YgfV6SO0
    depends_on:
      - redis
      - postgres

volumes:
  redis_data:
  postgres_data: